Final fixes for multiplatform building

diff --git a/Devtools/Singularity/ubuntu14.yml b/Devtools/Singularity/ubuntu14.yml
--- a/Devtools/Singularity/ubuntu14.yml
+++ b/Devtools/Singularity/ubuntu14.yml
@@ -60,6 +60,14 @@ From: ubuntu:14.04
     # Source conda
     . /opt/conda/etc/profile.d/conda.sh
 
+    # Make sure the GUI folder is present
+    if [ ! -d "GUI" ]; then
+        echo "GUI folder not found. Please run 'npm run buildparcel' first from a compatible system."
+        exit 1
+    fi
+
+    # Reinstall the conda environment
+    conda env remove -n horus_ubuntu14 --all -y
     conda env create -f Devtools/Environment/conda_horus.yaml -n horus_ubuntu14
 
     # Activate conda environment
